# golangci-lint v2 configuration
# See: https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    # --- Defaults (from staticcheck suite) ---
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    # --- Extended Best Practices ---
    - revive
    - gocritic
    - gosec
    - bodyclose
    - nilnil
    - unparam
    - misspell

formatters:
  enable:
    - gci

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/blockedby/positions-os)
  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
