FROM golang:1.25-alpine AS builder

WORKDIR /app


COPY go.mod go.sum ./
ENV GOPROXY=https://goproxy.io,direct
RUN go mod download

COPY . .

RUN go build -o /analyzer ./cmd/analyzer

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /analyzer .
# Copy prompts required by analyzer
COPY --from=builder /app/docs/prompts ./docs/prompts

CMD ["./analyzer"]
